### ISSUE TITLE
CMK 1.6

### ISSUE THREAD

**Issue by wernermarcel1** [ImTheLucKyOne/check_mk_emcunity#17]
Hi, 

we upgraded to 1.6 and realized that the check is not running. 

2019-10-16 09:33:00,055 [40] [cmk.web 19058] Failed to load plugin 
 /local/share/check_mk/web/plugins/metrics/emcunity.py: name 'df_translation' is not defined
Traceback (most recent call last):
  File "lib/python/cmk/gui/utils.py", line 173, in load_web_plugins
    execfile(file_path, globalvars)
  File "local/share/check_mk/web/plugins/metrics/emcunity.py", line 4, in <module>
    check_metrics["check_mk-emcunity_pool"]			= df_translation

I know that is untested but has you any hints for me ? 

rg
marcel

**Comment by ImTheLucKyOne** [comment]
Hi Marcel,

I will have a look into this. Thank you for reporting!

Regards
Philipp

**Comment by ImTheLucKyOne** [comment]
Hi Marcel,

as a workaround, please append the content of 

~/local/share/check_mk/web/plugins/metrics/emcunity.py

to

~/lib/python/cmk/gui/plugins/metrics/check_mk.py

With the update to cmk 1.6 they moved the place where all the web plugins resided and it seems like check_mk does not register and read the python file in the "local" path anymore so the metric value translation does not work correctly anymore.

PS:

On a fresh cmk1.6.0p5 installation I was able to monitor my unity without any major errors. Just the metric calculation was wrong. Moving stated content to the new location fixed it, so I hope it will fix your bigger error aswell. I will head out to the cmk on the mailing list because of that. Please report if the workaround works for you.

**Comment by wernermarcel1** [comment]
Hi ,

you workarounf worked.

Im on 1.6P3. at the moment.

Rg
Marcel

--

**Comment by gurubert** [comment]
df_translation needs to be imported in 1.6:

from cmk.gui.plugins.metrics.check_mk import df_translation
